apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: example
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: sharp-voyage-345407
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: asia-northeast3-a
          # name of the GKE cluster
          clusterName: test
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: sharp-voyage-345407
          # reference the sa from above
          serviceAccountRef:
            name: sa
            namespace: es